### ISSUE TITLE
Error when upload image

### ISSUE THREAD

**Issue by exaline-ru** [SunLabDev/oc-unsplashforblog-plugin#1]
Symfony\Component\Debug\Exception\FatalThrowableError: Class 'October\Rain\Support\Facades\Validator' not found in /home/admin/web/domain.com/public_html/plugins/sunlab/unsplashpicker/formwidgets/UnsplashPicker.php:77

**Comment by pavlorenc** [comment]
same error here. Any update of this?

**Comment by RomainMazB** [comment]
[Fixed into 1.0.4](https://github.com/SunLabDev/oc-unsplashpicker-plugin/pull/3), thanks for the report and sorry for the elapsed time!

The [Rain Validator wrapper](https://github.com/octobercms/library/commit/4405f43ab620031cbc5f88ad8145e0c812cdb41b#diff-2ac352318ffd3892ff2e749ddd175a1e8f198f8a1108ffd2f8fcf83542d2a5b8) has been deleted, the plugin will now directly rely on the Laravel's class
